name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      id-token: write

    environment:
      name: npm
      url: https://www.npmjs.com/package/@cssnr/vitepress-swiper

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Debug Event"
        continue-on-error: true
        run: |
          echo "ref: ${{ github.ref }}"
          echo "event_name: ${{ github.event_name }}"
          echo "github.event.repository.name: ${{ github.event.repository.name }}"

          echo "::group::cat event.json"
          cat "${GITHUB_EVENT_PATH}"
          echo "::endgroup::"

      - name: "Update Package Version"
        uses: cssnr/update-json-value-action@v1
        with:
          file: "package.json"

      - name: "Debug Package File"
        continue-on-error: true
        run: |
          cat package.json

      - name: "Setup Node"
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: "Install"
        run: |
          npm ci

      - name: "Publish"
        if: ${{ !github.event.release.prerelease }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --provenance --access public

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v5
        continue-on-error: true
        with:
          name: dist
          path: dist

      - name: "Archive Distribution"
        continue-on-error: true
        run: |
          zip -r dist.zip dist package.json README.md LICENSE

      - name: "Upload Release"
        if: ${{ github.event_name == 'release' }}
        uses: cssnr/upload-release-action@v1
        continue-on-error: true
        with:
          files: dist.zip

      - name: "Update Release Notes Action"
        uses: smashedr/update-release-notes-action@master
        continue-on-error: true
        with:
          location: tail

      - name: "Package Changelog Action"
        continue-on-error: true
        uses: cssnr/package-changelog-action@v2

      - name: "Send Failure Notification"
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@b8381b25576cb341b2af39926ab42c5056cc44ed # v1.15.5
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
